[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "altair>=6.0.0",
    "marimo>=0.18.0",
    "numpy>=2.3.5",
    "openai>=2.11.0",
    "polars>=1.35.2",
    "python-lsp-server>=1.14.0",
    "ruff>=0.14.9",
    "sympy>=1.14.0",
    "ty>=0.0.1a34",
]

[tool.hatch.build.targets.wheel]
packages = ["src/scratch"]
